Feature/us 72
alkemyTech/OT188-server pull request #48
Opened 2022-04-24 14:04 UTC by feyaluciano

2022-04-25 12:36 UTC, emmanuelranone requested changes
En principio al código lo veo bien. Pero me estás enviando en el mismo pr historias diferentes.
Veo código de comments y organization. Eso hay que dividirlo.
Adicionalmente, hay que agregar descripción de lo realizado en el commit y capturas que evidencien el funcionamiento del endpoint.

2022-04-25 17:44 UTC, feyaluciano commented
> 

lo que pasó es que faltaba el controlador de comentarios, y al no encontrarlo lo agregue, era de otra tarea, pero se nos pasó que faltaba

2022-05-01 21:12 UTC, feyaluciano commented
![image](https://user-images.githubusercontent.com/18562089/166164808-ceb647a7-560b-402e-bfa6-4d44ab29a170.png)

2022-05-02 12:18 UTC, emmanuelranone approved these changes

2022-05-02 12:18 UTC, merged