added Post method in contact endpoint
alkemyTech/OT188-server pull request #67
Opened 2022-04-30 21:37 UTC by JVita-Code

- created RegisterContactDto
- added RegisterContactDto to mapper classes
- added logic to insert a new Contact
- added Post method to controller

Screenshots:

Valid data:
![image](https://user-images.githubusercontent.com/85233653/166123343-1d980615-c5d1-4ef6-a71d-bc970c1513cd.png)

Invalid data: 
![image](https://user-images.githubusercontent.com/85233653/166123370-bc592c40-1e03-4ced-a20e-6f6cc905479a.png)

Exception (e.g: database is down)
![image](https://user-images.githubusercontent.com/85233653/166123447-8a59165b-8a40-41e7-b8f8-6d6cec2689fd.png)

2022-04-30 21:55 UTC, JVita-Code commented
Me equivoqué al registrar el horario de la historia... me tomó unas 9hs mas o menos, un par de horas por día hasta que nos pusimos de acuerdo con la clase Response

2022-05-01 00:06 UTC, emmanuelranone requested changes
El código está bien. Pero hay que revisar el error 500. Una api no debería devolver ese error, tenes que controlarlo en una excepción y devolver otra cosa.

2022-05-02 14:05 UTC, JVita-Code commented
El último conflict me pidió que comittee newDto y commentDto que fueron errores que surgieron por otro lado...

2022-05-02 15:36 UTC, emmanuelranone approved these changes

2022-05-02 15:36 UTC, merged